"use client";
import {
  IBM_Plex_Sans_Thai,
  Noto_Sans_Thai,
  Prompt,
  Montserrat,
} from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { redirect, usePathname } from "next/navigation";
import { userStore } from "./store/user_store";
import { useEffect, useState } from "react";
import Navbar from "./components/Navbar";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const ibmPlexSansThai = IBM_Plex_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const notosansthai = Noto_Sans_Thai({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const prompt = Prompt({
  subsets: ["latin", "thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  const getPath = usePathname();

  const isNothing = getPath === "/";

  const { isAuthenticated } = userStore();

  useEffect(() => {
    let isMounted = true;

    if (isMounted) {
      if (isAuthenticated === false && getPath !== "/") {
        redirect("/");
      }
    }

    return () => {
      isMounted = false;
    };
  }, []);

  return (
    <html lang="en" className={isNothing ? "bg-cubic-black" : ""}>
      <body
        // className={notosansthai.className}
        className="font-Inter"
      >
        <div className={!isNothing ? "" : "bg-cubic-black "}>
          <div className="">
            <Navbar />
          </div>
          <main className={!isNothing ? "flex-grow" : ""}>
            <div className={!isNothing ? " bg-cubic-black pt-[80px]" : ""}>
              <div
                className={
                  !isNothing
                    ? "rounded-[20px]  bg-cubic-black min-h-screen"
                    : "bg-cubic-black min-h-screen"
                }
              >
                {children}
              </div>
            </div>
          </main>
        </div>
      </body>
    </html>
  );
}
