/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast-1",
  aws_cloud_logic_custom: [
    {
      name: "cubicapi",
      endpoint:
        "https://o7avsmcibk.execute-api.ap-southeast-1.amazonaws.com/dev",
      region: "ap-southeast-1",
    },
  ],
  aws_cognito_identity_pool_id:
    "ap-southeast-1:01b5baa2-15cd-434e-8b0c-63d304367a41",
  aws_cognito_region: "ap-southeast-1",
  aws_user_pools_id: "ap-southeast-1_hWUqVTbkg",
  aws_user_pools_web_client_id: "2137tcdk9qua1a3n0m3r2lsihg",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: [],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket:
    "cubicadminddb288dae560483ca52316caecbc358fe16e9-dev",
  aws_user_files_s3_bucket_region: "ap-southeast-1",
};

export default awsmobile;
